# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GameAI.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cGameAI.proto\">\n\x11\x42oardStateRequest\x12)\n\nboardArray\x18\x01 \x03(\x0b\x32\x15.SingleDimensionArray\"%\n\x14SingleDimensionArray\x12\r\n\x05\x61rray\x18\x01 \x03(\x05\"!\n\x0b\x43olumnReply\x12\x12\n\nbestColumn\x18\x01 \x01(\x05\x32:\n\x06GameAi\x12\x30\n\x0cGiveBestMove\x12\x12.BoardStateRequest\x1a\x0c.ColumnReplyB(\n$code.controller.communication.gameaiP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GameAI_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals['DESCRIPTOR']._options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n$code.controller.communication.gameaiP\001'
    _globals['_BOARDSTATEREQUEST']._serialized_start = 16
    _globals['_BOARDSTATEREQUEST']._serialized_end = 78
    _globals['_SINGLEDIMENSIONARRAY']._serialized_start = 80
    _globals['_SINGLEDIMENSIONARRAY']._serialized_end = 117
    _globals['_COLUMNREPLY']._serialized_start = 119
    _globals['_COLUMNREPLY']._serialized_end = 152
    _globals['_GAMEAI']._serialized_start = 154
    _globals['_GAMEAI']._serialized_end = 212
# @@protoc_insertion_point(module_scope)
